### PR TITLE
Use ReproducibleBuilds and Update

### PR DESCRIPTION
**Pull request by kfrancis**
Running into the following: "Could not load file or assembly 'CoreCompat.Portable.Licensing' or one of its dependencies. Strong name signature could not be verified".

You can reproduce this if you: Create a .NET Full Framework asp.net website and add the CoreCompat.Portable.Licensing library and then try and run it. You'll immediately get the error.

Here's what I've done:

- Switched to using the [DotNet.ReproducableBuilds](https://github.com/dotnet/reproducible-builds) package so that you get all the green checks in NuGet and you don't need to specifically reference the source link lib, it'll do that itself.
- Updated from the .NET 4.5 references to .NET 4.8. (Opinion) At this point, if people are still on .NET Full Framework then they should at the very least be on 4.8.
- Added .NET 6.0 as a target, why not?
- Updated all the dependencies

22-03-izse5-1646859727

### CODE REVIEW

**Comment by kfrancis** [comment]
@qmfrederik ping

**Comment by qmfrederik** [comment]
@kfrancis Thanks for the PR. We have customer on an old .NET version so the 4.8 update may be problematic. I don't object to most of the other changes, but I'm not sure how any of those changes fixes the "Could not load file or assembly 'CoreCompat.Portable.Licensing' or one of its dependencies. Strong name signature could not be verified" issue.

Can you clarify which of the changes actually fixes the issue?

**Comment by kfrancis** [comment]
I don't know yet for sure, I'll play around and let you know. Curious though, migrating from 4.5 to 4.8 is "trivial" as they are in-place updates. Are you sure the client can't move up to at least the last (still not supported by Microsoft) version?

**Comment by kfrancis** [comment]
I just don't want to have to release a different fork on top of the already forked mess of the original project. One answer might be to add the reference libs in per framework, then it should work for both.

**Comment by kfrancis** [comment]
@qmfrederik How about this? Rather than replacing net48, just adding net45 and net48 with their own ref assemblies conditionally? That should make everyone happy.

Screenshot 2022-03-15 120932

**Comment by qmfrederik** [comment]
@kfrancis I just wonder whether your issue is not caused by a combination of these:

- The [`PublicSign` property is set to `true` when building on any non-Windows OS](https://github.com/CoreCompat/Portable.Licensing/blame/a3e5e5996db89d6f0a803bbec196dc5eaa2c174d/src/Portable.Licensing/Portable.Licensing.csproj#L10)
- CI (from which the official files are released) runs on Linux

If that's the case, it works with local builds because you're building on Linux.

I'm not sure why [public signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md) is enabled in the first place (may be a left-over) but I think it could cause the symptoms you describe. It may be a left-over of building on early versions of .NET Core where assembly signing was not supported on Linux.

Would you mind creating a PR which just removes the `PublicSign` property in `src/Portable.Licensing/Portable.Licensing.csproj` alltogether? I think this could fix your problem.

I don't necessarily object to the other changes you've made (other than `net45`, which we discussed) but would like to have the "one PR, one fix" approach.

**Comment by kfrancis** [comment]
I don't think that would be the issue, as I'm only using Windows and I can easily reproduce the issue there.

**Comment by kfrancis** [comment]
I'll close this and approach from a "one PR, one fix"

**Comment by qmfrederik** [comment]
> I don't think that would be the issue, as I'm only using Windows and I can easily reproduce the issue there.

But you're consuming the NuGet package, right (which was built on Linux)?

**Pull request closed without merging**
