### PR TITLE
Update PCL to .NET Standard

### PR DESCRIPTION
**Pull request by kfrancis**
I've updated the solution to target .NET Standard 2.0 now, since that's the standard "base" that Microsoft wants everyone to target. I have a solution that I want to use the licensing library for (I've used it in the past for a .NET 4.5 project) but this new project targets NetStandard2.

### CODE REVIEW

**Comment by qmfrederik** [comment]
@kfrancis Thanks for the PR.

[Version 1.1.5-r16 of CoreCompat.Portable.Licensing](https://www.nuget.org/packages/CoreCompat.Portable.Licensing/1.1.5-r16) already targets `netstandard2.0`. The source is on the features/dotnetcore-v2 branch.

Does that version work for you?

I don't own the upstream project, though.

**Comment by kfrancis** [comment]
Sure, that works - sorry, I didn't see that.

**Comment by nikro412956** [comment]
@qmfrederik is project still being worked on?

**Comment by qmfrederik** [comment]
Well, we use it and try to keep the library up to date whenever a new version of .NET Core ships, but that's pretty much it.

Are you looking for something in particular?

**Comment by nikro412956** [comment]
@qmfrederik well i was looking around on nuget for the portable.licensing package and i saw multiple including this one... i was wondering if the nuget package is up to date with this.
I am currently doing research in what is the best method of licensing for C# packages.

**Comment by nikro412956** [comment]
Just wondering but since you are using this did you have any problem with piracy or anything?

**Comment by qmfrederik** [comment]
The 1.1.5-r16 package is up to date. The code hasn't change much since upstream published it in 2013. You can take that as an indicating that the package is mature, but that there may be newer (and perhaps better) alternatives on NuGet :smile: .

**Comment by nikro412956** [comment]
ah good to know.
also i am searching for a specific method because i need to license Umbraco packages which has it's own difficulties.
thank you for the quick response!

**Comment by nikro412956** [comment]
@qmfrederik can i ask you how you prevent people from altering your licensing dll?

**Pull request closed without merging**
